// <auto-generated />
using System;
using IncidentApp.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IncidentApp.Migrations
{
    [DbContext(typeof(IncidentContext))]
    partial class IncidentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IncidentApp.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("FechaRegistro")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("CreadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("Borrado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Nombre")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Status")
                        .HasColumnName("Estatus")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("UpdaterId");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("IncidentApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BornDate")
                        .HasColumnName("FechaNacimiento")
                        .HasColumnType("datetime");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnName("Cedula")
                        .HasColumnType("varchar(11)")
                        .HasMaxLength(11);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("FechaRegistro")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("CreadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnName("Correo")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("Borrado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("Apellido")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Nombre")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("PhoneNumber")
                        .HasColumnName("Telefono")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<int>("PositionId")
                        .HasColumnName("PuestoId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnName("Estatus")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("UpdaterId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnName("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("PositionId");

                    b.HasIndex("UpdaterId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("IncidentApp.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IncidenteId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedUserId")
                        .HasColumnName("UsuarioAsignadoId")
                        .HasColumnType("int");

                    b.Property<string>("ClosedComment")
                        .HasColumnName("ComentarioCierre")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnName("FechaCierre")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("FechaRegistro")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("CreadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnName("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("Borrado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PriorityId")
                        .HasColumnName("PrioridadId")
                        .HasColumnType("int");

                    b.Property<int>("ReportedUserId")
                        .HasColumnName("UsuarioReportaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnName("Estatus")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("Titulo")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("UpdaterId");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("IncidentApp.Models.IncidentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("HistorialIncidenteId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnName("Comentario")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("FechaRegistro")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("CreadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int>("IncidentId")
                        .HasColumnName("IncidenteId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("Borrado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Status")
                        .HasColumnName("Estatus")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("IncidentId");

                    b.HasIndex("UpdaterId");

                    b.ToTable("HistorialIncidentes");
                });

            modelBuilder.Entity("IncidentApp.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PuestoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("FechaRegistro")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("CreadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnName("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("Borrado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Nombre")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Status")
                        .HasColumnName("Estatus")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UpdaterId");

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("IncidentApp.Models.Priority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PrioridadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("FechaRegistro")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("CreadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("Borrado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Nombre")
                        .HasColumnType("text");

                    b.Property<int>("SLAId")
                        .HasColumnName("SLAId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnName("Estatus")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("SLAId");

                    b.HasIndex("UpdaterId");

                    b.ToTable("Prioridades");
                });

            modelBuilder.Entity("IncidentApp.Models.SLA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SLAId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("FechaRegistro")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("CreadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("Hours")
                        .HasColumnName("CantidadHoras")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("Borrado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Status")
                        .HasColumnName("Estatus")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("UpdaterId");

                    b.ToTable("SLAs");
                });

            modelBuilder.Entity("IncidentApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("FechaRegistro")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("CreadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("Borrado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("Contrasena")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnName("Estatus")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("UpdaterId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnName("NombreUsuario")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("UpdaterId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 0,
                            IsDeleted = false,
                            Password = "ylwYeR9FMHE=",
                            Status = "1",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = 0,
                            Username = "Administrator"
                        });
                });

            modelBuilder.Entity("IncidentApp.Models.Department", b =>
                {
                    b.HasOne("IncidentApp.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("IncidentApp.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterId");
                });

            modelBuilder.Entity("IncidentApp.Models.Employee", b =>
                {
                    b.HasOne("IncidentApp.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("IncidentApp.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentApp.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterId");

                    b.HasOne("IncidentApp.Models.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("IncidentApp.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IncidentApp.Models.Incident", b =>
                {
                    b.HasOne("IncidentApp.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IncidentApp.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("IncidentApp.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("IncidentApp.Models.Priority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentApp.Models.User", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IncidentApp.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterId");
                });

            modelBuilder.Entity("IncidentApp.Models.IncidentHistory", b =>
                {
                    b.HasOne("IncidentApp.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("IncidentApp.Models.Incident", "Incident")
                        .WithMany("IncidentHistory")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentApp.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterId");
                });

            modelBuilder.Entity("IncidentApp.Models.Position", b =>
                {
                    b.HasOne("IncidentApp.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("IncidentApp.Models.Department", "Department")
                        .WithMany("Positions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentApp.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterId");
                });

            modelBuilder.Entity("IncidentApp.Models.Priority", b =>
                {
                    b.HasOne("IncidentApp.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("IncidentApp.Models.SLA", "SLA")
                        .WithMany()
                        .HasForeignKey("SLAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentApp.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterId");
                });

            modelBuilder.Entity("IncidentApp.Models.SLA", b =>
                {
                    b.HasOne("IncidentApp.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("IncidentApp.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterId");
                });

            modelBuilder.Entity("IncidentApp.Models.User", b =>
                {
                    b.HasOne("IncidentApp.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("IncidentApp.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterId");
                });
#pragma warning restore 612, 618
        }
    }
}
